### ISSUE TITLE
10-tygodniowy semest/kurs

### ISSUE THREAD

**Issue by teamon** [teamon/plan-pwr.pl#11]
- Da sie to jakos odczytac z edukacji? - Da sie wyciagnac numer semestru
- Ustawienie reczne per semestr - koliduje przy kilku kierunkach
- Ustawienie reczne per kurs - troche sporo klikania

**Comment by paciks** [comment]
Co do ustawiania to można by zrobić listę z wszystkimi kursami wczytanymi z edukacji a przy nich 'check-button'y. Użytkownik zaznacza który kurs ma być liczony jako 10 tygodniowy i wtedy plan ulega aktualizacji. Aktualizacji dlatego, że większość osób będzie mieć kursy 15 tygodniowe oraz często osoby które są na semestrach 15 tygodniowych realizują sobie kursy z semestrów 10 tygodniowych :)
